### PR TITLE
Add Metapath default function to registry: implicit-timezone, current-date, current-time

### PR DESCRIPTION
**Pull request by aj-stein-gsa**
# Committer Notes

Part of #162 (but does not close it).

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/metaschema-framework/metaschema-java/blob/main/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/metaschema-framework/metaschema-java/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Have you set "[Allow edits and access to secrets by maintainers](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?

By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public domain](https://creativecommons.org/publicdomain/zero/1.0/) dedication.

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all website and readme documentation affected by the changes you made?

### CODE REVIEW

**Comment by david-waltermire** [comment]
I think for `current-time` you will need to implement the [time data type](https://www.w3.org/TR/xmlschema-2/#time).

**Comment by david-waltermire** [comment]
We probably want to have the time and time-with-timezone variants. I believe this implementation can be backed with a [ZonedDateTime](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/ZonedDateTime.html), where the date is defaulted and ignored.

**Comment by david-waltermire** [comment]
@aj-stein-gsa Please rebase this to pickup the latest build automation.

**Comment by david-waltermire** [comment]
I implemented implicit-timezone and current-time in #265. `current-date` is still needed.

**Comment by aj-stein-gsa** [comment]
> I implemented implicit-timezone and current-time in #265. `current-date` is still needed.

OK, great, I will not close then and work it.

**Comment by david-waltermire** [comment]
Added support for current-date in #274.

**Pull request closed without merging**
